baseURL: http://example.org/
languageCode: en
title: ''
theme: hugo-devresume-theme
googleAnalytics: UA-XXXXXXX-Y
params:
  author: alandmanurung
  awards:
    enable: yes
    list:
      - body: Runner Up English Debate
        date: '2019'
        name: AAPG Unpad SC
  contact:
    enable: yes
    list:
      - icon: fas fa-phone-square
        text: '+447424918407'
        url: tel:#
      - icon: fas fa-envelope-square
        text: aem33@student.le.ac.uk
        url: mailto:#
      - icon: fas fa-globe
        text: alandmanurung.github.io
        url: '#'
    location: Leicester
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  education:
    enable: yes
    list:
      - dates: 2021 - 2022
        degree: MSc in Satellite Data Science
        university: University of Leicester
      - dates: 2016 - 2020
        degree: BSc in Geological Engineering
        university: Institut Teknologi Bandung
  experience:
    enable: yes
    list:
      - company: Kita Earth Ltd
        dates: May 2022 - Sep 2022
        details: Develop above ground biomass esimator using optical and SAR (if applicable)
          remote sensing data. Do carbon accounting using existing carbon model.
        title: Above Ground Biomass Analyst
      - company: University of Leicester
        dates: Jan 2022 - Mar 2022
        details: Developed machine learning model to predict biomass from LiDAR dataset
        items:
          - details: Pre-process LiDAR dataset into tabular format for machine learning
              model.
          - details: Communicate action plan for the whole team.
        title: Research Assistant
      - company: PT. Bhumi Varta Technology
        dates: May 2021 - Jul 2021
        details: Generate projects related to Geographical Information System (GIS) and
          satellite image processing.
        items:
          - details: Developed MOWL, mobile app of indoor GIS for shopping mall
          - details: Developed machine learning model for Land-use classification based
              on satellite imagery.
        title: GIS Developer Intern
  information:
    enable: yes
    list:
      - items:
          - details: Feb 2022 · BCG - Data Science and Advanced Data Analytics Virtual Experience Program
          - details: Feb 2022 · BCG - Data Science and Advanced Data Analytics Virtual Experience Program
          - details: Jan 2022 · Geo University - Overview of LiDAR; system variations, data interpretation & applications
          - details: Jul 2021 · Udemy - Geospatial Data Science with Python Geopandas
          - details: Jul 2021 · Udemy - Python for Data Science and Machine Learning Bootcamp
          - details: Apr 2021 · IHE Delft - Programming for Geospatial Hydrological Applications
          - details: Mar 2021 · Udemy - Core Spatial Data Analysis Introductory GIS with R and QGIS
          - details: Mar 2021 · Cisco Networking Academy - PCAP - Programming Essentials in Python English 0221b
          - details: Feb 2021 · Udemy - Web GIS Development Course 2020
        title: Certification
      - items:
          - details: Mar 2021 - Mar 2023 · IELTS (Overall 7.5)
        title: Qualification
  interests:
    enable: yes
    list:
      - name: Environment
      - name: Earth Observation
      - name: Carbon Monitoring
      - name: Travelling
      - name: Badminton
  languages:
    enable: yes
    list:
      - level: Upper Intermediate
        name: English
      - level: Native
        name: Indonesian
  primaryColor: '#2E5A88'
  profile:
    avatar: avatar_aland.png
    enable: yes
    name: Aland Edbert Manurung
    tagline: Geospatial Developer and Data Analyst
  projects:
    enable: yes
    list:
      - meta: University Module Coursework
        tagline: UAMS is a webapp to display PM2.5, CO, NO2, and SO2 on defined 
          month and year. Data were derived from CDS API from Copernicus 
          Atmosphere Monitoring Service and integrated with R Shiny. This project 
          is a group coursework project of Earth Observation of Atmosphere module 
          in University of Leicester, I worked as the developer of the webapp.
          Can be accessed through https://alandmanurung.shinyapps.io/pollutant-map/
        title: UAMS - Urban Air Monitoring System
  skills:
    enable: yes
    list:
      - items:
          - details: QGIS/ArcGIS
          - details: ERDAS Imagine
          - details: Python/R
          - details: PostgreSQL/PostGIS
          - details: Microsoft Office
          - details: Scribus/GIMP/Inkscape
          - details: Hitfilm
        title: Technical
  social:
    enable: yes
    list:
      - icon: fab fa-github-square
        title: alandmanurung
        url: //github.com/alandmanurung
      - icon: fab fa-linkedin
        title: alandmanurung
        url: //linkedin.com/in/alandmanurung
      - icon: fab fa-twitter-square
        title: '@AlandManurung'
        url: //twitter.com/AlandManurung
  summary:
    enable: yes
    text: Environmental geoscientist who is interested in carbon monitoring using satellite 
      images. Experienced in building land use models and using Geographic Information System 
      (GIS) for environmental changes. I am interested to learn more about LiDAR, 
      Hyperspectral Imagery, and biomass estimation.
  textPrimaryColor: '#292929'
